# Generated by Django 4.1.13 on 2024-07-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qualification_management', '0001_initial'),
        ('Student_Management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Qualification_management.qualification'),
        ),
    ]
