# Generated by Django 4.1.13 on 2024-07-12 00:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management', '0003_student_subjects'),
        ('Subject_content_management', '0003_subject_alter_subjectcontent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcontent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjectcontent',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Management.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
