# Generated by Django 5.0.6 on 2024-07-05 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
