# Generated by Django 5.0.6 on 2024-07-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_management', '0003_user_created_at_user_updated_at_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lecturer', 'Lecturer'), ('student', 'Student')], max_length=20),
        ),
    ]
