# Generated by Django 4.1.13 on 2024-07-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_management', '0004_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
