# Generated by Django 4.1.13 on 2024-07-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_management', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lecturer', 'Lecturer'), ('student', 'Student')], max_length=10),
        ),
    ]
